[package]
name = "gen_m3u"
version = "0.1.0"
authors = ["meuh"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tempfile = "3.1"